name: Fast build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Fast build on Windows

    runs-on: windows-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Visual Studio environment
      uses: egor-tensin/vs-shell@v2

    - name: Cache
      uses: actions/cache@v4.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: out/build
        # An explicit key for restoring and saving the cache
        key: fastBuild-out

    - name: Configure CMake
      run: cmake -S . -B out/build -DCMAKE_BUILD_TYPE=Release

    - name: Build all
      working-directory: out/build
      run: cmake --build .

    - name: Run all tests
      working-directory: out/build
      run: ctest .

    - name: Install package
      run: cmake --install out/build --prefix out/install

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: out/install
        # Duration after which artifact will expire in days. 0 means using default retention.
        #Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
        retention-days: 15
